/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentPendingRouteImport } from './routes/student.pending'
import { Route as StudentForumRouteImport } from './routes/student.forum'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCurriculumRouteImport } from './routes/student.curriculum'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as StudentCertificateRouteImport } from './routes/student.certificate'
import { Route as InstructorForumRouteImport } from './routes/instructor.forum'
import { Route as InstructorDashboardRouteImport } from './routes/instructor.dashboard'
import { Route as InstructorCreateRouteImport } from './routes/instructor.create'
import { Route as InstructorApprovalsRouteImport } from './routes/instructor.approvals'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor.analytics'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as StudentQuizIdRouteImport } from './routes/student.quiz.$id'
import { Route as StudentLessonLessonIdRouteImport } from './routes/student.lesson.$lessonId'
import { Route as StudentLearnIdRouteImport } from './routes/student.learn.$id'
import { Route as StudentAssignmentIdRouteImport } from './routes/student.assignment.$id'
import { Route as StudentAssessmentModuleIdRouteImport } from './routes/student.assessment.$moduleId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/student/progress',
  path: '/student/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPendingRoute = StudentPendingRouteImport.update({
  id: '/student/pending',
  path: '/student/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentForumRoute = StudentForumRouteImport.update({
  id: '/student/forum',
  path: '/student/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCurriculumRoute = StudentCurriculumRouteImport.update({
  id: '/student/curriculum',
  path: '/student/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/student/certificates',
  path: '/student/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCertificateRoute = StudentCertificateRouteImport.update({
  id: '/student/certificate',
  path: '/student/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorForumRoute = InstructorForumRouteImport.update({
  id: '/instructor/forum',
  path: '/instructor/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/instructor/dashboard',
  path: '/instructor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCreateRoute = InstructorCreateRouteImport.update({
  id: '/instructor/create',
  path: '/instructor/create',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorApprovalsRoute = InstructorApprovalsRouteImport.update({
  id: '/instructor/approvals',
  path: '/instructor/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/instructor/analytics',
  path: '/instructor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentQuizIdRoute = StudentQuizIdRouteImport.update({
  id: '/student/quiz/$id',
  path: '/student/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLessonLessonIdRoute = StudentLessonLessonIdRouteImport.update({
  id: '/student/lesson/$lessonId',
  path: '/student/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLearnIdRoute = StudentLearnIdRouteImport.update({
  id: '/student/learn/$id',
  path: '/student/learn/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssignmentIdRoute = StudentAssignmentIdRouteImport.update({
  id: '/student/assignment/$id',
  path: '/student/assignment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssessmentModuleIdRoute =
  StudentAssessmentModuleIdRouteImport.update({
    id: '/student/assessment/$moduleId',
    path: '/student/assessment/$moduleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/courses/$id': typeof CoursesIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/approvals': typeof InstructorApprovalsRoute
  '/instructor/create': typeof InstructorCreateRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/forum': typeof InstructorForumRoute
  '/student/certificate': typeof StudentCertificateRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/forum': typeof StudentForumRoute
  '/student/pending': typeof StudentPendingRoute
  '/student/progress': typeof StudentProgressRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/student/assessment/$moduleId': typeof StudentAssessmentModuleIdRoute
  '/student/assignment/$id': typeof StudentAssignmentIdRoute
  '/student/learn/$id': typeof StudentLearnIdRoute
  '/student/lesson/$lessonId': typeof StudentLessonLessonIdRoute
  '/student/quiz/$id': typeof StudentQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/courses/$id': typeof CoursesIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/approvals': typeof InstructorApprovalsRoute
  '/instructor/create': typeof InstructorCreateRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/forum': typeof InstructorForumRoute
  '/student/certificate': typeof StudentCertificateRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/forum': typeof StudentForumRoute
  '/student/pending': typeof StudentPendingRoute
  '/student/progress': typeof StudentProgressRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/student/assessment/$moduleId': typeof StudentAssessmentModuleIdRoute
  '/student/assignment/$id': typeof StudentAssignmentIdRoute
  '/student/learn/$id': typeof StudentLearnIdRoute
  '/student/lesson/$lessonId': typeof StudentLessonLessonIdRoute
  '/student/quiz/$id': typeof StudentQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/courses/$id': typeof CoursesIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/approvals': typeof InstructorApprovalsRoute
  '/instructor/create': typeof InstructorCreateRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/forum': typeof InstructorForumRoute
  '/student/certificate': typeof StudentCertificateRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/forum': typeof StudentForumRoute
  '/student/pending': typeof StudentPendingRoute
  '/student/progress': typeof StudentProgressRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/student/assessment/$moduleId': typeof StudentAssessmentModuleIdRoute
  '/student/assignment/$id': typeof StudentAssignmentIdRoute
  '/student/learn/$id': typeof StudentLearnIdRoute
  '/student/lesson/$lessonId': typeof StudentLessonLessonIdRoute
  '/student/quiz/$id': typeof StudentQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/courses/$id'
    | '/instructor/analytics'
    | '/instructor/approvals'
    | '/instructor/create'
    | '/instructor/dashboard'
    | '/instructor/forum'
    | '/student/certificate'
    | '/student/certificates'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/forum'
    | '/student/pending'
    | '/student/progress'
    | '/verify/$token'
    | '/student/assessment/$moduleId'
    | '/student/assignment/$id'
    | '/student/learn/$id'
    | '/student/lesson/$lessonId'
    | '/student/quiz/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/courses/$id'
    | '/instructor/analytics'
    | '/instructor/approvals'
    | '/instructor/create'
    | '/instructor/dashboard'
    | '/instructor/forum'
    | '/student/certificate'
    | '/student/certificates'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/forum'
    | '/student/pending'
    | '/student/progress'
    | '/verify/$token'
    | '/student/assessment/$moduleId'
    | '/student/assignment/$id'
    | '/student/learn/$id'
    | '/student/lesson/$lessonId'
    | '/student/quiz/$id'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/courses/$id'
    | '/instructor/analytics'
    | '/instructor/approvals'
    | '/instructor/create'
    | '/instructor/dashboard'
    | '/instructor/forum'
    | '/student/certificate'
    | '/student/certificates'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/forum'
    | '/student/pending'
    | '/student/progress'
    | '/verify/$token'
    | '/student/assessment/$moduleId'
    | '/student/assignment/$id'
    | '/student/learn/$id'
    | '/student/lesson/$lessonId'
    | '/student/quiz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRoute
  InstructorApprovalsRoute: typeof InstructorApprovalsRoute
  InstructorCreateRoute: typeof InstructorCreateRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorForumRoute: typeof InstructorForumRoute
  StudentCertificateRoute: typeof StudentCertificateRoute
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentCurriculumRoute: typeof StudentCurriculumRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentForumRoute: typeof StudentForumRoute
  StudentPendingRoute: typeof StudentPendingRoute
  StudentProgressRoute: typeof StudentProgressRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  StudentAssessmentModuleIdRoute: typeof StudentAssessmentModuleIdRoute
  StudentAssignmentIdRoute: typeof StudentAssignmentIdRoute
  StudentLearnIdRoute: typeof StudentLearnIdRoute
  StudentLessonLessonIdRoute: typeof StudentLessonLessonIdRoute
  StudentQuizIdRoute: typeof StudentQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/student/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/pending': {
      id: '/student/pending'
      path: '/student/pending'
      fullPath: '/student/pending'
      preLoaderRoute: typeof StudentPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/forum': {
      id: '/student/forum'
      path: '/student/forum'
      fullPath: '/student/forum'
      preLoaderRoute: typeof StudentForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/curriculum': {
      id: '/student/curriculum'
      path: '/student/curriculum'
      fullPath: '/student/curriculum'
      preLoaderRoute: typeof StudentCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/student/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/certificate': {
      id: '/student/certificate'
      path: '/student/certificate'
      fullPath: '/student/certificate'
      preLoaderRoute: typeof StudentCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/forum': {
      id: '/instructor/forum'
      path: '/instructor/forum'
      fullPath: '/instructor/forum'
      preLoaderRoute: typeof InstructorForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/instructor/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/create': {
      id: '/instructor/create'
      path: '/instructor/create'
      fullPath: '/instructor/create'
      preLoaderRoute: typeof InstructorCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/approvals': {
      id: '/instructor/approvals'
      path: '/instructor/approvals'
      fullPath: '/instructor/approvals'
      preLoaderRoute: typeof InstructorApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/instructor/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/quiz/$id': {
      id: '/student/quiz/$id'
      path: '/student/quiz/$id'
      fullPath: '/student/quiz/$id'
      preLoaderRoute: typeof StudentQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/lesson/$lessonId': {
      id: '/student/lesson/$lessonId'
      path: '/student/lesson/$lessonId'
      fullPath: '/student/lesson/$lessonId'
      preLoaderRoute: typeof StudentLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/learn/$id': {
      id: '/student/learn/$id'
      path: '/student/learn/$id'
      fullPath: '/student/learn/$id'
      preLoaderRoute: typeof StudentLearnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assignment/$id': {
      id: '/student/assignment/$id'
      path: '/student/assignment/$id'
      fullPath: '/student/assignment/$id'
      preLoaderRoute: typeof StudentAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assessment/$moduleId': {
      id: '/student/assessment/$moduleId'
      path: '/student/assessment/$moduleId'
      fullPath: '/student/assessment/$moduleId'
      preLoaderRoute: typeof StudentAssessmentModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesIdRoute: typeof CoursesIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesIdRoute: CoursesIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  InstructorAnalyticsRoute: InstructorAnalyticsRoute,
  InstructorApprovalsRoute: InstructorApprovalsRoute,
  InstructorCreateRoute: InstructorCreateRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorForumRoute: InstructorForumRoute,
  StudentCertificateRoute: StudentCertificateRoute,
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentCurriculumRoute: StudentCurriculumRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentForumRoute: StudentForumRoute,
  StudentPendingRoute: StudentPendingRoute,
  StudentProgressRoute: StudentProgressRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  StudentAssessmentModuleIdRoute: StudentAssessmentModuleIdRoute,
  StudentAssignmentIdRoute: StudentAssignmentIdRoute,
  StudentLearnIdRoute: StudentLearnIdRoute,
  StudentLessonLessonIdRoute: StudentLessonLessonIdRoute,
  StudentQuizIdRoute: StudentQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
